-- Atomic cart checkout and itemized order history for the scanner workflow.

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  checkout_token uuid not null unique,
  camper_id uuid not null references public.campers(id) on delete restrict,
  total_cents integer not null check (total_cents > 0),
  item_count integer not null check (item_count > 0),
  note text,
  status text not null default 'completed' check (status in ('completed', 'voided')),
  performed_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  voided_at timestamptz
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete restrict,
  store_item_id uuid references public.store_items(id) on delete set null,
  item_name text not null,
  barcode_value text,
  unit_price_cents integer not null check (unit_price_cents > 0),
  quantity integer not null check (quantity > 0),
  line_total_cents integer not null check (line_total_cents > 0),
  created_at timestamptz not null default now()
);

alter table public.transactions
  add column if not exists order_id uuid references public.orders(id) on delete set null;

create index if not exists orders_camper_created_at_idx
  on public.orders (camper_id, created_at desc);

create index if not exists order_items_order_id_idx
  on public.order_items (order_id);

create unique index if not exists transactions_order_id_key
  on public.transactions (order_id)
  where order_id is not null;

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

revoke all on table public.orders from anon, authenticated;
revoke all on table public.order_items from anon, authenticated;
grant select on table public.orders to authenticated;
grant select on table public.order_items to authenticated;

drop policy if exists "authenticated users can read orders" on public.orders;
create policy "authenticated users can read orders"
on public.orders
for select to authenticated
using (auth.uid() is not null);

drop policy if exists "authenticated users can read order items" on public.order_items;
create policy "authenticated users can read order items"
on public.order_items
for select to authenticated
using (auth.uid() is not null);

create or replace function public.complete_camper_order(
  p_camper_id uuid,
  p_lines jsonb,
  p_note text,
  p_checkout_token uuid
)
returns table (
  success boolean,
  message text,
  new_balance_cents integer,
  order_id uuid,
  order_number bigint,
  total_cents integer,
  item_count integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current_balance integer;
  v_new_balance integer;
  v_total integer := 0;
  v_item_count integer := 0;
  v_line jsonb;
  v_item public.store_items%rowtype;
  v_item_id uuid;
  v_quantity integer;
  v_custom_amount integer;
  v_label text;
  v_order_id uuid;
  v_order_number bigint;
  v_existing public.orders%rowtype;
begin
  if auth.uid() is null then
    return query
      select false, 'Not signed in.', null::integer, null::uuid, null::bigint,
             null::integer, null::integer;
    return;
  end if;

  if p_checkout_token is null then
    return query
      select false, 'Checkout token is required.', null::integer, null::uuid, null::bigint,
             null::integer, null::integer;
    return;
  end if;

  select *
  into v_existing
  from public.orders
  where checkout_token = p_checkout_token;

  if found then
    if v_existing.camper_id <> p_camper_id then
      return query
        select false, 'Checkout token does not match this camper.', null::integer,
               null::uuid, null::bigint, null::integer, null::integer;
      return;
    end if;

    select balance_cents into v_current_balance
    from public.campers
    where id = v_existing.camper_id;

    return query
      select true,
             'Order #' || v_existing.order_number || ' was already completed.',
             v_current_balance,
             v_existing.id,
             v_existing.order_number,
             v_existing.total_cents,
             v_existing.item_count;
    return;
  end if;

  if p_lines is null
     or jsonb_typeof(p_lines) <> 'array'
     or jsonb_array_length(p_lines) = 0 then
    return query
      select false, 'Add at least one item before checkout.', null::integer, null::uuid,
             null::bigint, null::integer, null::integer;
    return;
  end if;

  for v_line in select value from jsonb_array_elements(p_lines)
  loop
    v_quantity := coalesce((v_line->>'quantity')::integer, 0);
    if v_quantity <= 0 or v_quantity > 100 then
      return query
        select false, 'Each cart quantity must be between 1 and 100.', null::integer,
               null::uuid, null::bigint, null::integer, null::integer;
      return;
    end if;

    v_item_id := nullif(v_line->>'item_id', '')::uuid;

    if v_item_id is not null then
      select *
      into v_item
      from public.store_items
      where id = v_item_id and is_active = true;

      if not found then
        return query
          select false, 'A store item is missing or inactive.', null::integer, null::uuid,
                 null::bigint, null::integer, null::integer;
        return;
      end if;

      v_total := v_total + (v_item.price_cents * v_quantity);
    else
      v_custom_amount := coalesce((v_line->>'custom_amount_cents')::integer, 0);
      if v_custom_amount <= 0 then
        return query
          select false, 'Custom cart amounts must be greater than 0.', null::integer,
                 null::uuid, null::bigint, null::integer, null::integer;
        return;
      end if;
      v_total := v_total + (v_custom_amount * v_quantity);
    end if;

    v_item_count := v_item_count + v_quantity;
  end loop;

  select balance_cents
  into v_current_balance
  from public.campers
  where id = p_camper_id
  for update;

  if not found then
    return query
      select false, 'Camper not found.', null::integer, null::uuid, null::bigint,
             null::integer, null::integer;
    return;
  end if;

  if v_current_balance < v_total then
    return query
      select false, 'Insufficient funds.', v_current_balance, null::uuid, null::bigint,
             v_total, v_item_count;
    return;
  end if;

  v_new_balance := v_current_balance - v_total;

  insert into public.orders as new_order (
    checkout_token,
    camper_id,
    total_cents,
    item_count,
    note,
    performed_by
  )
  values (
    p_checkout_token,
    p_camper_id,
    v_total,
    v_item_count,
    nullif(trim(p_note), ''),
    auth.uid()
  )
  returning new_order.id, new_order.order_number into v_order_id, v_order_number;

  for v_line in select value from jsonb_array_elements(p_lines)
  loop
    v_quantity := (v_line->>'quantity')::integer;
    v_item_id := nullif(v_line->>'item_id', '')::uuid;

    if v_item_id is not null then
      select * into v_item from public.store_items where id = v_item_id;

      insert into public.order_items (
        order_id,
        store_item_id,
        item_name,
        barcode_value,
        unit_price_cents,
        quantity,
        line_total_cents
      )
      values (
        v_order_id,
        v_item.id,
        v_item.item_name,
        v_item.barcode_value,
        v_item.price_cents,
        v_quantity,
        v_item.price_cents * v_quantity
      );
    else
      v_custom_amount := (v_line->>'custom_amount_cents')::integer;
      v_label := coalesce(nullif(trim(v_line->>'label'), ''), 'Custom charge');

      insert into public.order_items (
        order_id,
        item_name,
        unit_price_cents,
        quantity,
        line_total_cents
      )
      values (
        v_order_id,
        v_label,
        v_custom_amount,
        v_quantity,
        v_custom_amount * v_quantity
      );
    end if;
  end loop;

  update public.campers
  set balance_cents = v_new_balance
  where id = p_camper_id;

  insert into public.transactions (
    camper_id,
    order_id,
    transaction_type,
    amount_cents,
    note,
    performed_by
  )
  values (
    p_camper_id,
    v_order_id,
    'charge',
    v_total,
    'Order #' || v_order_number || ' - ' || v_item_count || ' item'
      || case when v_item_count = 1 then '' else 's' end,
    auth.uid()
  );

  return query
    select true,
           'Order #' || v_order_number || ' charged successfully.',
           v_new_balance,
           v_order_id,
           v_order_number,
           v_total,
           v_item_count;
end;
$$;

revoke all on function public.complete_camper_order(uuid, jsonb, text, uuid) from public;
grant execute on function public.complete_camper_order(uuid, jsonb, text, uuid) to authenticated;

create or replace function public.void_charge_transaction(
  p_transaction_id uuid
)
returns table (
  success boolean,
  message text,
  new_balance_cents integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_original public.transactions%rowtype;
  v_current_balance integer;
  v_new_balance integer;
begin
  if auth.uid() is null then
    return query select false, 'Not signed in.', null::integer;
    return;
  end if;

  select *
  into v_original
  from public.transactions
  where id = p_transaction_id
  for update;

  if not found then
    return query select false, 'Transaction not found.', null::integer;
    return;
  end if;

  if v_original.transaction_type <> 'charge' then
    return query select false, 'Only charge transactions can be voided.', null::integer;
    return;
  end if;

  if v_original.voided_at is not null then
    return query select false, 'That transaction has already been voided.', null::integer;
    return;
  end if;

  select balance_cents
  into v_current_balance
  from public.campers
  where id = v_original.camper_id
  for update;

  if not found then
    return query select false, 'Camper account not found.', null::integer;
    return;
  end if;

  v_new_balance := v_current_balance + v_original.amount_cents;

  update public.campers
  set balance_cents = v_new_balance
  where id = v_original.camper_id;

  insert into public.transactions (
    camper_id,
    transaction_type,
    amount_cents,
    note,
    performed_by,
    voided_transaction_id
  )
  values (
    v_original.camper_id,
    'void',
    v_original.amount_cents,
    case
      when v_original.order_id is not null then 'Void for order charge ' || v_original.id
      else 'Void for transaction ' || v_original.id
    end,
    auth.uid(),
    v_original.id
  );

  update public.transactions
  set voided_at = now()
  where id = v_original.id;

  if v_original.order_id is not null then
    update public.orders
    set status = 'voided',
        voided_at = now()
    where id = v_original.order_id;
  end if;

  return query select true, 'Charge voided.', v_new_balance;
end;
$$;

revoke all on function public.void_charge_transaction(uuid) from public;
grant execute on function public.void_charge_transaction(uuid) to authenticated;
